<?php

namespace App\Console\Commands;

use App\Services\ImageService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class ImportHojas extends Command
{
    protected $signature = 'import:hojas
        {--host=127.0.0.1 : MySQL v1 host}
        {--port=3306 : MySQL v1 port}
        {--database= : MySQL v1 database name (required)}
        {--username=root : MySQL v1 username}
        {--password= : MySQL v1 password}
        {--dry-run : Preview record counts without saving}';

    protected $description = 'Unified import: hoja_chequeos + chequeo_diarios → v2 structure. Run import:equipos and import:users first.';

    // v1 area → v2 turno_id / centro_costo_id
    private const AREA_MAP = [
        'cuarto de maquinas' => ['turno_id' => 4, 'centro_costo_id' => 3],
        'tintoreria' => ['turno_id' => 1, 'centro_costo_id' => 1],
    ];

    private const AREA_DEFAULT = ['turno_id' => 3, 'centro_costo_id' => 2];

    // answer_type_id constants (match DatabaseSeeder / answer_types table)
    private const TYPE_ICON = 1; // icon_set  — simbologia_id answer

    private const TYPE_NUMERIC = 2; // number    — numeric valor

    private const TYPE_TEXT = 3; // text      — text valor

    public function handle(): int
    {
        if (! $this->option('database')) {
            $this->error('--database is required.');

            return self::FAILURE;
        }

        config()->set('database.connections.mysql_v1', [
            'driver' => 'mysql',
            'host' => $this->option('host'),
            'port' => $this->option('port'),
            'database' => $this->option('database'),
            'username' => $this->option('username'),
            'password' => $this->option('password'),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
        ]);

        DB::purge('mysql_v1');

        $this->info('Connecting to MySQL v1...');

        try {
            $hojas = DB::connection('mysql_v1')->table('hoja_chequeos')->get();
            $chequeos = DB::connection('mysql_v1')->table('chequeo_diarios')->get();
        } catch (\Exception $e) {
            $this->error('Connection failed: '.$e->getMessage());

            return self::FAILURE;
        }

        $this->info("Found {$hojas->count()} hoja_chequeos and {$chequeos->count()} chequeo_diarios in v1.");

        if ($this->option('dry-run')) {
            $this->table(['table', 'count'], [
                ['hoja_chequeos (v1)',    $hojas->count()],
                ['chequeo_diarios (v1)', $chequeos->count()],
            ]);

            return self::SUCCESS;
        }

        // ── Pre-build item_id → answer_type_id from actual execution data ──
        // One query across all item_chequeo_diarios — infers type from real answers
        // rather than guessing from the METODO JSON field.
        $this->info('Inferring answer types from execution data...');
        $itemTypeMap = $this->buildItemTypeMap();
        $this->line('  Done — '.count($itemTypeMap).' items typed.');

        // ══════════════════════════════════════════════════════════════════
        // PHASE 1 — hoja_chequeos → hoja_columnas + hoja_filas + valores
        // ══════════════════════════════════════════════════════════════════
        $this->info('Phase 1: importing hoja_chequeos…');

        $bar = $this->output->createProgressBar($hojas->count());
        $bar->start();

        // v1_hoja_id => ['v2_id' => int, 'area' => string]
        $hojaIdMap = [];
        $totalColumnas = 0;
        $totalFilas = 0;
        $totalValores = 0;

        foreach ($hojas as $hoja) {
            // ── hoja_chequeo ─────────────────────────────────────────────
            // Conflict on (equipo_id, version) to handle v1 duplicates.
            // ID is auto-generated by Postgres and read back below.
            DB::table('hoja_chequeos')->upsert(
                [
                    'equipo_id' => $hoja->equipo_id,
                    'version' => $hoja->version,
                    'observaciones' => $hoja->observaciones,
                    'encendido' => true,
                    'created_at' => $hoja->created_at,
                    'updated_at' => $hoja->updated_at,
                ],
                ['equipo_id', 'version'],
                ['observaciones', 'updated_at']
            );

            $v2HojaId = DB::table('hoja_chequeos')
                ->where('equipo_id', $hoja->equipo_id)
                ->where('version', $hoja->version)
                ->value('id');

            $hojaIdMap[$hoja->id] = [
                'v2_id' => $v2HojaId,
                'area' => $hoja->area ?? '',
            ];

            // ── items → columnas + filas + valores ───────────────────────
            $items = DB::connection('mysql_v1')
                ->table('items')
                ->where('hoja_chequeo_id', $hoja->id)
                ->orderBy('id')
                ->get();

            if ($items->isEmpty()) {
                $bar->advance();

                continue;
            }

            // Build columns from the JSON keys of the first item
            $firstValores = json_decode($items->first()->valores, true) ?? [];
            $columnaIdByKey = [];
            $colOrder = 0;

            foreach (array_keys($firstValores) as $jsonKey) {
                $key = strtolower($jsonKey);
                $label = ucfirst(strtolower($jsonKey));

                DB::table('hoja_columnas')->insertOrIgnore([
                    'hoja_chequeo_id' => $v2HojaId,
                    'key' => $key,
                    'label' => $label,
                    'is_fixed' => true,
                    'order' => $colOrder++,
                    'created_at' => $hoja->created_at,
                    'updated_at' => $hoja->updated_at,
                ]);

                $columnaIdByKey[$key] = DB::table('hoja_columnas')
                    ->where('hoja_chequeo_id', $v2HojaId)
                    ->where('key', $key)
                    ->value('id');

                $totalColumnas++;
            }

            $filaOrder = 0;

            foreach ($items as $item) {
                $valores = json_decode($item->valores, true) ?? [];

                // Type comes from actual execution data (simbologia_id → icon, numeric valor → number,
                // text valor → text). If this item has no executions yet, default to text.
                $answerTypeId = $itemTypeMap[$item->id] ?? self::TYPE_TEXT;

                // Use v1 item.id as hoja_fila.id — FK preserved for respuestas import
                DB::table('hoja_filas')->upsert(
                    [
                        'id' => $item->id,
                        'hoja_chequeo_id' => $v2HojaId,
                        'answer_type_id' => $answerTypeId,
                        'order' => $filaOrder++,
                        'categoria' => $item->categoria ?? 'limpieza',
                        'created_at' => $item->created_at,
                        'updated_at' => $item->updated_at,
                    ],
                    ['id'],
                    ['answer_type_id', 'order', 'categoria', 'updated_at']
                );

                $totalFilas++;

                foreach ($valores as $jsonKey => $cellValue) {
                    $key = strtolower($jsonKey);

                    if (! isset($columnaIdByKey[$key])) {
                        continue;
                    }

                    DB::table('hoja_fila_valors')->upsert(
                        [
                            'hoja_fila_id' => $item->id,
                            'hoja_columna_id' => $columnaIdByKey[$key],
                            'valor' => (string) $cellValue,
                            'created_at' => $item->created_at,
                            'updated_at' => $item->updated_at,
                        ],
                        ['hoja_fila_id', 'hoja_columna_id'],
                        ['valor', 'updated_at']
                    );

                    $totalValores++;
                }
            }

            $bar->advance();
        }

        $bar->finish();
        $this->newLine();

        foreach (['hoja_chequeos', 'hoja_columnas', 'hoja_filas', 'hoja_fila_valors'] as $table) {
            DB::statement("SELECT setval('{$table}_id_seq', (SELECT MAX(id) FROM {$table}))");
        }

        $this->info('Phase 1 done.');
        $this->line("  hoja_chequeos  : {$hojas->count()}");
        $this->line("  hoja_columnas  : {$totalColumnas}");
        $this->line("  hoja_filas     : {$totalFilas}");
        $this->line("  hoja_fila_valors: {$totalValores}");

        // ══════════════════════════════════════════════════════════════════
        // PHASE 2 — chequeo_diarios → hoja_ejecucions + hoja_fila_respuestas
        // ══════════════════════════════════════════════════════════════════
        $this->newLine();
        $this->info('Phase 2: importing chequeo_diarios…');

        $imageService = app(ImageService::class);
        $bar2 = $this->output->createProgressBar($chequeos->count());
        $bar2->start();

        $importedEjecuciones = 0;
        $totalRespuestas = 0;
        $firmaErrors = 0;

        foreach ($chequeos as $row) {
            $hojaInfo = $hojaIdMap[$row->hoja_chequeo_id] ?? null;

            if (! $hojaInfo) {
                $bar2->advance();

                continue; // hoja_chequeo wasn't imported
            }

            $v2HojaId = $hojaInfo['v2_id'];

            // ── Area-based turno / centro_costo mapping ───────────────────
            $areaKey = strtolower(trim($hojaInfo['area']));
            $mapping = self::AREA_MAP[$areaKey] ?? self::AREA_DEFAULT;

            // ── Signatures: v1 stores raw base64 URI, v2 expects file path ─
            $firmaOperador = null;
            $firmaSupervisor = null;

            if (! empty($row->firma_operador)) {
                try {
                    $firmaOperador = $imageService->storeBase64('firmas', $row->firma_operador);
                } catch (\Exception) {
                    $firmaErrors++;
                }
            }

            if (! empty($row->firma_supervisor)) {
                try {
                    $firmaSupervisor = $imageService->storeBase64('firmas', $row->firma_supervisor);
                } catch (\Exception) {
                    $firmaErrors++;
                }
            }

            // Bypass HojaEjecucionObserver::saved() — sends admin notifications
            // on every record where finalizado_en is not null (all of them)
            DB::table('hoja_ejecucions')->upsert(
                [
                    'id' => $row->id,
                    'hoja_chequeo_id' => $v2HojaId,
                    'user_id' => $row->operador_id,
                    'turno_id' => $mapping['turno_id'],
                    'centro_costo_id' => $mapping['centro_costo_id'],
                    'nombre_operador' => $row->nombre_operador,
                    'firma_operador' => $firmaOperador,
                    'firma_supervisor' => $firmaSupervisor,
                    'observaciones' => $row->observaciones,
                    'finalizado_en' => $row->created_at,
                    'created_at' => $row->created_at,
                    'updated_at' => $row->updated_at,
                ],
                ['id'],
                ['hoja_chequeo_id', 'user_id', 'turno_id', 'centro_costo_id', 'nombre_operador',
                    'firma_operador', 'firma_supervisor', 'observaciones', 'finalizado_en', 'updated_at']
            );

            $importedEjecuciones++;

            // ── hoja_fila_respuestas ──────────────────────────────────────
            $itemRows = DB::connection('mysql_v1')
                ->table('item_chequeo_diarios')
                ->where('chequeo_diario_id', $row->id)
                ->get();

            foreach ($itemRows as $item) {
                [$answerOptionId, $numericValue, $textValue] = $this->resolveAnswer($item);

                DB::table('hoja_fila_respuestas')->upsert(
                    [
                        'hoja_ejecucion_id' => $row->id,
                        'hoja_fila_id' => $item->item_id,
                        'answer_option_id' => $answerOptionId,
                        'numeric_value' => $numericValue,
                        'text_value' => $textValue,
                        'boolean_value' => null,
                        'created_at' => $item->created_at,
                        'updated_at' => $item->updated_at,
                    ],
                    ['hoja_ejecucion_id', 'hoja_fila_id'],
                    ['answer_option_id', 'numeric_value', 'text_value', 'boolean_value', 'updated_at']
                );

                $totalRespuestas++;
            }

            $bar2->advance();
        }

        $bar2->finish();
        $this->newLine();

        foreach (['hoja_ejecucions', 'hoja_fila_respuestas'] as $table) {
            DB::statement("SELECT setval('{$table}_id_seq', (SELECT MAX(id) FROM {$table}))");
        }

        $this->info('Phase 2 done.');
        $this->line("  hoja_ejecucions      : {$importedEjecuciones}");
        $this->line("  hoja_fila_respuestas : {$totalRespuestas}");

        if ($firmaErrors > 0) {
            $this->warn("  {$firmaErrors} firma(s) could not be stored and were set to NULL.");
        }

        return self::SUCCESS;
    }

    /**
     * Pre-build a map of v1 item_id → answer_type_id by sampling actual
     * execution data. One query for the entire dataset.
     *
     * Priority: simbologia_id → TYPE_ICON
     *           numeric valor → TYPE_NUMERIC
     *           text valor    → TYPE_TEXT
     */
    private function buildItemTypeMap(): array
    {
        $responses = DB::connection('mysql_v1')
            ->table('item_chequeo_diarios')
            ->select('item_id', 'simbologia_id', 'valor')
            ->get();

        $map = [];

        foreach ($responses as $resp) {
            if (isset($map[$resp->item_id])) {
                continue; // first sample wins
            }

            if ($resp->simbologia_id !== null) {
                $map[$resp->item_id] = self::TYPE_ICON;
            } elseif ($resp->valor !== null) {
                $map[$resp->item_id] = is_numeric($resp->valor)
                    ? self::TYPE_NUMERIC
                    : self::TYPE_TEXT;
            }
        }

        return $map;
    }

    /**
     * Resolve the correct answer fields from a v1 item_chequeo_diario row.
     *
     * Returns [answer_option_id, numeric_value, text_value].
     */
    private function resolveAnswer(object $item): array
    {
        if ($item->simbologia_id !== null) {
            return [$item->simbologia_id, null, null];
        }

        if ($item->valor !== null) {
            if (is_numeric($item->valor)) {
                return [null, (float) $item->valor, null];
            }

            return [null, null, (string) $item->valor];
        }

        return [null, null, null];
    }
}
